### ISSUE TITLE
Overflowing text

### ISSUE THREAD

**Issue by ghost** [mrgumminger/mrgumminger.github.io#3]
You're going to want to fix these small issues. Some of the text is flowing off the course-box sections. You may want to add some extra space to those elements.

![screen shot 2017-06-15 at 12 58 29 pm](https://user-images.githubusercontent.com/7355203/27192771-92095adc-51ca-11e7-91db-7a4947229b0a.png)

**Comment by mrgumminger** [comment]
Fixed height removed. Issues caused by development on a laptop without consideration for LARGER screens.
